apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j-k8s
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: log4j-k8s
  template:
    metadata:
      labels:
        app: log4j-k8s
    spec:
      containers:
      - image: ghcr.io/christophetd/log4shell-vulnerable-app
        imagePullPolicy: Always
        name: log4j-k8s
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-k8s
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: log4j-k8s
  sessionAffinity: None
  type: LoadBalancer
